{% set version = "3.5.2" %}
{% set sha256 = "5f245bd5176bc5f67428eb0aa497e09979264a153a074d35416521a5b8e86189" %}

package:
  name: libarchive-pkg
  version: "{{ version }}"

about:
  home: https://www.libarchive.org/
  license: BSD-2-Clause
  summary: "Multi-format archive and compression library"

source:
  url: https://github.com/libarchive/libarchive/releases/download/v{{ version }}/libarchive-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler("c") }}
    - make
    - pkg-config
  host:
    - libbz2-dev
    - liblzma-dev
    - libz-dev
  run:
    - libbz2
    - liblzma
    - libz

outputs:
  - name: libarchive
    files:
      - lib/libarchive.so*
    test:
      commands:
        - test -h ${PREFIX}/lib/libarchive.so
        - test -f $( readlink -f ${PREFIX}/lib/libarchive.so )

  - name: libarchive-dev
    files:
      - include/archive.h
      - include/archive_entry.h
      - lib/libarchive.a
      - lib/pkgconfig/libarchive.pc
      - share/man/man3
      - share/man/man5
    requirements:
      run:
        - {{ pin_subpackage("libarchive", exact=True) }}
    test:
      commands:
        - test -f ${PREFIX}/include/archive.h
        - test -f ${PREFIX}/lib/libarchive.a

  - name: libarchive-bin
    files:
      - bin/bsd*
      - share/man/man1
    test:
      commands:
        - test -f ${PREFIX}/bin/bsdcat
        - test -f ${PREFIX}/bin/bsdcpio
        - test -f ${PREFIX}/bin/bsdtar
