{% set version = "7.58.0" %}
{% set sha256 = "1cb081f97807c01e3ed747b6e1c9fee7a01cb10048f1cd0b5f56cfe0209de731" %}

package:
  name: curl-pkg
  version: "{{ version }}"

about:
  home: http://curl.haxx.se/
  license: MIT
  summary: Command line tool and library for transferring data with URLs.

build:
  number: 6

source:
  - url: http://curl.haxx.se/download/curl-{{ version }}.tar.bz2
    sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - libgnutls-dev
    - libnettle-dev
    - libz-dev
  run:
    - libgnutls
    - libnettle
    - libz
    - ca-certificates

outputs:
  - name: curl
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - make
      host:
        - libgnutls-dev
        - libnettle-dev
        - libz-dev
      run:
        - {{ pin_subpackage("libcurl", exact=True) }}
        - libgnutls
        - libnettle
        - libz
    files:
      - bin/curl
      - bin/curl-config
      - share/man/man1/curl.1
      - share/man/man1/curl-config.1
    test:
      commands:
        - curl -h
        - curl -LI https://google.com

  - name: libcurl
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - make
      host:
        - libgnutls-dev
        - libnettle-dev
        - libz-dev
      run:
        - libgnutls
        - libnettle
        - libz
        - ca-certificates
    files:
      - lib/libcurl.a
      - lib/libcurl.so*
    test:
      commands:
        - test -f ${PREFIX}/lib/libcurl.a
        - test -h ${PREFIX}/lib/libcurl.so

  - name: libcurl-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libcurl", exact=True) }}
    files:
      - include/curl
      - lib/pkgconfig/libcurl.pc
      - share/man/man4/libcurl*
    test:
      commands:
        - test -f ${PREFIX}/include/curl/curl.h
