{% set version = "0.7.17" %}

package:
  name: bwa-aligner
  version: "{{ version }}"

about:
  home: https://github.com/lh3/bwa
  license: GPLv3
  summary: Burrows-Wheeler Aligner for short-read alignment.

build:
  number: 1

source:
  - git_url: https://github.com/lh3/bwa.git
    git_rev: v{{ version }}

    patches:
      - Makefile.patch

requirements:
  build:
    - zlib

  run:
    - zlib

test:
  commands:
    - test -x ${PREFIX}/bin/bwa
