{% set version = "1.14.11" %}
{% set sha256 = "a172cb66416794fdd9c1fc443f722f7e3439b52c99510b9a60f828392b9989e4" %}

package:
  name: io_lib-pkg
  version: "{{ version }}"

about:
  home: https://sourceforge.net/projects/staden
  license: BSD
  summary: DNA sequence assembly, editing and analysis tools.

build:
  number: 4

source:
  url: https://github.com/jkbonfield/io_lib/releases/download/io_lib-1-14-11/io_lib-{{ version }}.tar.gz
  fn: io_lib-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - make
  host:
    - irods-dev {{ irods }}
    - libbz2-dev
    - libcurl-dev
    - liblzma-dev
    - libz-dev
  run:
    - libbz2
    - libcurl
    - liblzma
    - libz

outputs:
  - name: io_lib
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
      host:
        - libbz2-dev
        - libcurl-dev
        - liblzma-dev
        - libz-dev
      run:
        - {{ pin_subpackage("libstaden-read", exact=True) }}
        - libbz2
        - libcurl
        - liblzma
        - libz
    files:
      - bin/append_sff
      - bin/convert_trace
      - bin/cram_dump
      - bin/cram_filter
      - bin/cram_index
      - bin/cram_size
      - bin/extract_fastq
      - bin/extract_qual
      - bin/extract_seq
      - bin/get_comment
      - bin/hash_exp
      - bin/hash_extract
      - bin/hash_list
      - bin/hash_sff
      - bin/hash_tar
      - bin/index_tar
      - bin/makeSCF
      - bin/scf_dump
      - bin/scf_info
      - bin/scf_update
      - bin/scram_flagstat
      - bin/scram_merge
      - bin/scram_pileup
      - bin/scram_test
      - bin/scramble
      - bin/srf2fasta
      - bin/srf2fastq
      - bin/srf_dump_all
      - bin/srf_extract_hash
      - bin/srf_extract_linear
      - bin/srf_filter
      - bin/srf_index_hash
      - bin/srf_info
      - bin/srf_list
      - bin/trace_dump
      - bin/ztr_dump
      - share/man/man1/scramble.1
      - share/man/man1/srf2fasta.1
      - share/man/man1/srf2fastq.1
      - share/man/man1/srf_index_hash.1
      - share/man/man1/srf_info.1
      - share/man/man1/srf_list.1
    test:
      commands:
        - scramble -h

  - name: libstaden-read
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
      host:
        - libbz2-dev
        - libcurl-dev
        - liblzma-dev
        - libz-dev
      run:
        - libbz2
        - libcurl
        - liblzma
        - libz
    files:
      - lib/libstaden-read*
    test:
      commands:
        - test -f ${PREFIX}/lib/libstaden-read.a
        - test -h ${PREFIX}/lib/libstaden-read.so

  - name: libstaden-read-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libstaden-read", exact=True) }}
    files:
      - bin/io_lib-config
      - include/io_lib
      - share/man/man3/ExperimentFile.3
      - share/man/man3/exp2read.3
      - share/man/man3/fread_reading.3
      - share/man/man3/fread_scf.3
      - share/man/man3/fwrite_reading.3
      - share/man/man3/fwrite_scf.3
      - share/man/man3/read2exp.3
      - share/man/man3/read2scf.3
      - share/man/man3/read_allocate.3
      - share/man/man3/read_deallocate.3
      - share/man/man3/read_reading.3
      - share/man/man3/read_scf.3
      - share/man/man3/read_scf_header.3
      - share/man/man3/scf2read.3
      - share/man/man3/write_reading.3
      - share/man/man3/write_scf.3
      - share/man/man3/write_scf_header.3
      - share/man/man4/Read.4
    test:
      commands:
        - test -f ${PREFIX}/include/io_lib/io_lib_config.h
