{% set version = "3.10.4" %}
{% set sha256 = "1155fd1a83049767360e9a120c43c578145db3204d2b309eba49fbbedd0f4ed3" %}

package:
  name: json
  version: "{{ version }}"

about:
  home: https://json.nlohmann.me/
  license: MIT
  summary: "JSON for Modern C++ is a C++11 JSON parser"

source:
  url: https://github.com/nlohmann/json/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make

files:
  - include/nlohmann/
  - lib/pkgconfig/nlohmann_json.pc
  - lib/cmake/nlohmann_json/

test:
  commands:
    - test -f ${PREFIX}/include/nlohmann/json.hpp
