{% set version = "1.73.0" %}
{% set alt_version = "1_73_0" %}
{% set sha256 = "4eb3b8d442b426dc35346235c8733b5ae35ba431690e38c6a8263dce9fcbb402" %}

package:
  name: boost
  version: "{{ version }}"

about:
  home: "http://www.boost.org"
  license: Other
  summary: "Free peer-reviewed portable C++ source libraries."

build:
  number: 0

source:
  url: https://dl.bintray.com/boostorg/release/{{ version }}/source/boost_{{ alt_version }}.tar.bz2
  fn: boost_{{ alt_version }}.tar.bz2
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - make
  host:
    - libbz2-dev
    - liblzma-dev
    - libz-dev
  run:
    - libbz2
    - liblzma
    - libz

outputs:
  - name: libboost
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("cxx") }}
        - make
      host:
        - libbz2-dev
        - liblzma-dev
        - libz-dev
      run:
        - libbz2
        - liblzma
        - libz
    files:
      - lib/libboost*.so*
    test:
      commands:
        - test -h ${PREFIX}/lib/libboost_system.so

  - name: libboost-dev
    version: {{ version }}
    requirements:
      run:
        - {{ pin_subpackage("libboost", exact=True) }}
    files:
      - include/boost
      - lib/cmake
      - lib/libboost*.a
    test:
      commands:
        - test -f ${PREFIX}/include/boost/config.hpp
