*** Makefile	2010-09-10 23:46:02.000000000 +0100
--- Makefile.patch	2018-09-05 14:36:38.896339103 +0100
***************
*** 15,31 ****
  SHELL=/bin/sh
  
  # To assist in cross-compiling
! CC=gcc
! AR=ar
! RANLIB=ranlib
! LDFLAGS=
  
  BIGFILES=-D_FILE_OFFSET_BITS=64
! CFLAGS=-Wall -Winline -O2 -g $(BIGFILES)
  
  # Where you want it installed when you do 'make install'
! PREFIX=/usr/local
! 
  
  OBJS= blocksort.o  \
        huffman.o    \
--- 15,29 ----
  SHELL=/bin/sh
  
  # To assist in cross-compiling
! CC?=gcc
! AR?=ar
! RANLIB?=ranlib
  
  BIGFILES=-D_FILE_OFFSET_BITS=64
! CFLAGS?=-Wall -Winline -O2 -g $(BIGFILES)
  
  # Where you want it installed when you do 'make install'
! PREFIX="$PREFIX"
  
  OBJS= blocksort.o  \
        huffman.o    \
