--- src/Makefile	2018-09-06 14:29:54.549708722 +0000
+++ src/Makefile.libs	2018-09-07 10:48:00.212875012 +0000
@@ -46,7 +46,7 @@
 .PHONY: all static debug profiling gprof

 $(HTSLIB_ROOT)/libhts.a:
-	cd $(HTSLIB_ROOT) && make
+	cd $(HTSLIB_ROOT) && make LDFLAGS="-L$PREFIX/lib" CPPFLAGS="-I$PREFIX/include"

 $(SEQLIB_ROOT)/src/libseqlib.a:
 	cd $(SEQLIB_ROOT) && ./configure && make
