--- vcflib/tabixpp/Makefile	2018-09-06 14:30:22.309883227 +0000
+++ vcflib/tabixpp/Makefile.lib	2018-09-07 12:54:14.400585361 +0000
@@ -35,7 +35,7 @@
 	$(CXX) $(CXXFLAGS) -c tabix.cpp $(INCLUDES)

 htslib/libhts.a:
-	cd htslib && $(MAKE) lib-static
+	cd htslib && $(MAKE) lib-static LDFLAGS="-L$(PREFIX)/lib" CPPFLAGS="-I$(PREFIX)/include"

 tabix++: tabix.o main.cpp $(HTS_LIB)
 	$(CXX) $(CXXFLAGS) -o $@ main.cpp tabix.o $(INCLUDES) $(LIBPATH) \
