diff --git a/c/Makefile b/c/Makefile
index 95111d7..6a75389 100644
--- a/c/Makefile
+++ b/c/Makefile
@@ -21,14 +21,14 @@
 VERSION=$(shell perl -I../lib -MPCAP -e 'print PCAP->VERSION;')
 
 #Compiler
-CC = gcc -O3 -DVERSION='"$(VERSION)"' -g
+CC ?= gcc -O3 -DVERSION='"$(PKG_VERSION)"' -g
 
 #CC = gcc -O3 -DVERSION='"$(VERSION)"' -g
 
 #compiler flags
 # -g adds debug info to the executable file
 # -Wall turns on most warnings from compiler
-CFLAGS = -Wall
+CFLAGS ?= -Wall
 
 
 HTSLOC?=$(HTSLIB)
@@ -92,7 +92,7 @@ all: clean pre make_htslib_tmp $(BAM_STATS_TARGET) $(BAM2BG_TARGET) $(BAM2BW_TAR
 	@echo  bam_stats and reheadSQ compiled.
 
 $(BAM_STATS_TARGET): $(OBJS)
-	$(CC) $(CFLAGS) $(INCLUDES) $(CAT_INCLUDES) -o $(BAM_STATS_TARGET) $(OBJS) $(LFLAGS) $(CAT_LFLAGS) $(LIBS) ./bam_stats.c
+	$(CC) $(CFLAGS) $(CPPFLAGS) $(INCLUDES) -o $(BAM_STATS_TARGET) $(OBJS) $(LFLAGS) $(LDFLAGS) $(LIBS) ./bam_stats.c
 
 $(SQ_TARGET):
 	$(CC) $(CFLAGS) ./reheadSQ.c -o $(SQ_TARGET)
@@ -139,7 +139,7 @@ valgrind:
 # the rule(a .c file) and $@: the name of the target of the rule (a .o file)
 # (see the gnu make manual section about automatic variables)
 .c.o:
-	$(CC) $(CFLAGS) $(INCLUDES) $(CAT_INCLUDES) -c $<  -o $@
+	$(CC) $(CFLAGS) $(INCLUDES) $(CPPFLAGS) -c $<  -o $@
 
 clean:
 	@echo clean
