#!/bin/sh

set -ex

n="$CPU_COUNT"

# This is not a configure script that was generated by GNU
# autoconf. It does not process extra comman line options, which is
# why configuration is set in the environment and passed as arguments
# to make.
prefix="$PREFIX" CC="$GCC" ./configure

make -j "$n" CC="$GCC" CPPFLAGS="-I$PREFIX/include" LDFLAGS="-L$PREFIX/lib"
make install
