{% set version = "3.3" %}
{% set sha256 = "46942627d5d0ca11720fec18d81fc38f7ef837ea4197c1f630e71ce0d470b11e" %}

package:
  name: nettle
  version: "{{ version }}"

about:
  home: https://www.lysator.liu.se/~nisse/nettle/
  license: GPL2 
  summary: A low-level cryptographic library

build:
  number: 1

source:
  url: https://ftp.gnu.org/gnu/nettle/nettle-{{ version }}.tar.gz
  fn: nettle-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - gcc_npg >=7.3
    - gmplib >=5.0

test:
  commands:
    - test -f ${PREFIX}/include/nettle/sha1.h
    - test -f ${PREFIX}/lib/libnettle.a
    - test -h ${PREFIX}/lib/libnettle.so
    - test -f ${PREFIX}/lib/libhogweed.a
    - test -h ${PREFIX}/lib/libhogweed.so
