{% set gittag = "201712" %}
{% set version = "201712+irods_4.2.8" %}

package:
  name: htslib-plugins
  version: "{{ version }}"

about:
  home: https://github.com/samtools/htslib
  license: MIT
  summary: C library for high-throughput sequencing data formats.

build:
  number: 1

source:
  - git_url: https://github.com/samtools/htslib-plugins.git
    git_rev: {{ gittag }}
    folder: plugins

requirements:
  build:
    - {{ compiler("c") }}
    - autoconf
    - automake
    - make
    - perl
  host:
    - irods-dev ==4.2.8
    - libbz2-dev
    - libcurl-dev
    - libdeflate-dev
    - libhts-dev
    - liblzma-dev
    - libssl-dev
    - libz-dev
  run:
    - libbz2
    - libcurl
    - libdeflate
    - liblzma
    - libssl
    - libz
    - irods-runtime ==4.2.8

outputs:
  - name: libhts-plugins
    version: {{ version }}
    requirements:
      build:
        - {{ compiler("c") }}
        - autoconf
        - automake
        - make
        - perl
      host:
        - irods-dev ==4.2.8
        - libbz2-dev
        - libcurl-dev
        - libdeflate-dev
        - libhts-dev
        - liblzma-dev
        - libssl-dev
        - libz-dev
      run:
        - libbz2
        - libcurl
        - libdeflate
        - libhts
        - liblzma
        - libssl
        - libz
        - irods-runtime ==4.2.8
    files:
      - libexec/htslib/hfile_irods.so
      - libexec/htslib/hfile_irods_wrapper.so
      - libexec/htslib/hfile_mmap.so
    test:
      commands:
        - test -f ${PREFIX}/libexec/htslib/hfile_irods.so
        - test -f ${PREFIX}/libexec/htslib/hfile_irods_wrapper.so
