{% set version = "2.9.7" %}
{% set sha256 = "f63c5e7d30362ed28b38bfa1ac6313f9a80230720b7fb6c80575eeab3ff5900c" %}

package:
  name: libxml2-pkg
  version: "{{ version }}"

about:
  home: http://www.xmlsoft.org/
  license: MIT
  summary: "XML C parser and toolkit developed for the Gnome project."

build:
  number: 3

source:
  url: ftp://xmlsoft.org/libxml2/libxml2-{{ version }}.tar.gz
  fn: libxml2-{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler("c") }}
    - make
  host:
    - liblzma-dev
    - libz-dev
  run:
    - liblzma
    - libz

outputs:
  - name: libxml2-bin
    requirements:
      build:
        - {{ compiler("c") }}
        - make
      host:
        - liblzma-dev
        - libz-dev
      run:
        - {{ pin_subpackage('libxml2', exact=True) }}
        - liblzma
        - libz
    files:
      - bin/xml2-config
      - bin/xmlcatalog
      - bin/xmllint
    test:
      commands:
        - test -f ${PREFIX}/lib/libxml2.a
        - test -h ${PREFIX}/lib/libxml2.so

  - name: libxml2
    requirements:
      build:
        - {{ compiler("c") }}
        - make
      host:
        - liblzma-dev
        - libz-dev
      run:
        - liblzma
        - libz
    files:
      - lib/libxml2.*
    test:
      commands:
        - test -f ${PREFIX}/lib/libxml2.a
        - test -h ${PREFIX}/lib/libxml2.so

  - name: libxml2-dev
    requirements:
      run:
         {{ pin_subpackage('libxml2', exact=True) }}
    files:
      - include/libxml2
      - lib/xml2Conf.sh
      - lib/pkgconfig/libxml-2.0.pc
      - share/doc/libxml2-{{ version }}
      - share/gtk-doc/html/libxml2
    test:
      commands:
        - test -f ${PREFIX}/include/libxml2/libxml/uri.h
